name: GameSelect Auto Update

on:
  schedule:
    - cron: '0 14 * * *'  # every day at 14:00 UTC
  workflow_dispatch:     # allow manual run from GitHub UI

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    - name: Run update script
      run: python update_db.py

    - name: Commit and push if changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add game_database.csv data/
        git diff --quiet && git diff --staged --quiet || git commit -m "🔄 Daily DB update"
        git push
